trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  project: '**/*.csproj'
  outputPath: '$(Build.ArtifactStagingDirectory)/publish'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET Core SDK'
  inputs:
    packageType: 'sdk'
    version: '8.x'
    installationPath: $(Agent.ToolsDirectory)/dotnet

- task: DotNetCoreCLI@2
  displayName: 'Restaurar paquetes'
  inputs:
    command: 'restore'
    projects: '$(project)'

- task: DotNetCoreCLI@2
  displayName: 'Compilar proyecto'
  inputs:
    command: 'build'
    projects: '$(project)'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Publicar proyecto'
  inputs:
    command: 'publish'
    publishWebProjects: true
    arguments: '--configuration $(buildConfiguration) --output $(outputPath)'

- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefactos'
  inputs:
    pathToPublish: '$(outputPath)'
    artifactName: 'drop'
